chore: add GetFilteredGroups GetRepository GetRepositoryFor
jenkins-x-plugins/jx-gitops pull request #852
Opened 2022-06-17 13:20 UTC by JordanGoasdoue

Issue from jx-slack where it doesn't find configuration for one of my repositories

I have repositories, splitted into 2 different groups just because it doesn't use the same scheduler

on the case the kind, gitserver url and owner is the same on both group, the function GetOrCreateGroup will just take the first group, even if my repository is on the second one

in order to fix this I have- create Get only function in order to get the right repository on jx-slack

2022-06-21 03:19 UTC, ankitm123 commented
Would be nice if u run the linter - the linting issues are unrelated to ur PR changes btw ... (should be quick)

2022-08-05 12:28 UTC, ankitm123 commented
/ok-to-test

2022-08-05 12:56 UTC, ankitm123 commented
```


pkg/sourceconfigs/helpers.go:141:2: rangeValCopy: each iteration copies 152 bytes (consider pointers or indexing) (gocritic)
--
  |   |   |   | for _, group := range groups {
  |   |   |   | ^
  |   |   |   | pkg/sourceconfigs/helpers.go:194:2: rangeValCopy: each iteration copies 152 bytes (consider pointers or indexing) (gocritic)
  |   |   |   | for _, group := range groups {


```

2022-08-09 14:40 UTC, JordanGoasdoue commented
@ankitm123 this time it's good :ok_hand:

2022-08-22 14:25 UTC, tomhobson requested changes

2022-08-22 14:25 UTC, tomhobson commented on pkg/sourceconfigs/helpers_test.go
> +	assertSlackChannel(t, config, "no-cfg", "repo-enabled", "default-channel-for-orgs", v1alpha1.PipelineKindRelease, false, false, true)
Any with expected repo false?
If not -- is there any point in changing this test :) 

Maybe would be nice to whack a couple in

2022-08-22 14:52 UTC, tomhobson approved these changes

2022-08-22 15:06 UTC, merged