fix: correct sign of offset and negation of expression
jenkins-x-plugins/jx-gitops pull request #922
Opened 2023-03-23 16:31 UTC by msvticket

Fix to make it work like intended in #920

2023-03-23 16:38 UTC, msvticket commented
You are welcome to check as well @Skisocks

2023-03-27 13:46 UTC, msvticket commented
/cc ankitm123 babadofar

2023-03-29 10:08 UTC, tomhobson approved these changes

2023-03-29 10:09 UTC, Skisocks approved these changes

2023-03-29 10:10 UTC, merged

2023-03-29 10:10 UTC, tomhobson requested changes

2023-03-29 10:10 UTC, tomhobson commented on pkg/cmd/helmfile/status/status_test.go
> +func TestHemlfileStatus_WithEarlyCutoff(t *testing.T) {
Can you spell helmfile right -- it's frustrating me :)

2023-03-29 10:11 UTC, tomhobson commented on pkg/cmd/helmfile/status/status_test.go
> +func TestHemlfileStatus_WithEarlyCutoff(t *testing.T) {
damn missed the merge window